import '../config/config_loader.dart';
import 'theme_scanner.dart';

/// Generates `design_qa.yaml`.
///
/// A fresh file is templated with comments so an empty stub is still
/// self-documenting. Re-running against an existing file only ever
/// *appends* newly discovered routes as a text-level edit rather than
/// re-serializing the whole document from a parsed model - so a designer's
/// hand-edited tokens, comments, and mock args from a previous run survive
/// exactly as written. See doc/design_qa_yaml_reference.md.
class YamlWriter {
  const YamlWriter();

  String generateFresh({required ScannedTokens tokens, required List<String> routes}) {
    final StringBuffer out = StringBuffer();
    out.writeln('# design_qa.yaml - generated by `dart run design_qa:init`.');
    out.writeln('# Edit freely; re-running init only ever appends newly found routes.');
    out.writeln('# Full reference: package:design_qa/doc/design_qa_yaml_reference.md');
    out.writeln();
    out.writeln('tokens:');
    if (tokens.isEmpty) {
      out.writeln('  # No token source found automatically (this recognizes classes made of');
      out.writeln('  # `static const` Color/double fields - see the reference doc for other');
      out.writeln('  # patterns and how to list them here by hand). Example shape:');
      out.writeln('  # colors:');
      out.writeln("  #   primary: '#FF2962FF'");
      out.writeln('  # spacing:');
      out.writeln('  #   md: 16');
      out.writeln('  colors: {}');
      out.writeln('  spacing: {}');
      out.writeln('  radius: {}');
    } else {
      if (tokens.source != null) out.writeln('  source: ${tokens.source}');
      out.writeln('  colors:');
      if (tokens.colors.isEmpty) out.writeln('    {}');
      for (final MapEntry<String, String> e in tokens.colors.entries) {
        out.writeln("    ${e.key}: '${e.value}'");
      }
      out.writeln('  spacing:');
      if (tokens.spacing.isEmpty) out.writeln('    {}');
      for (final MapEntry<String, double> e in tokens.spacing.entries) {
        out.writeln('    ${e.key}: ${_fmt(e.value)}');
      }
      out.writeln('  radius:');
      if (tokens.radius.isEmpty) out.writeln('    {}');
      for (final MapEntry<String, double> e in tokens.radius.entries) {
        out.writeln('    ${e.key}: ${_fmt(e.value)}');
      }
    }
    out.writeln();
    out.writeln('routes:');
    if (routes.isEmpty) {
      out.writeln('  # No named routes found automatically. Add screens that need arguments');
      out.writeln('  # with mockArgs so they render without navigating through the real flow:');
      out.writeln('  # - name: /profile');
      out.writeln("  #   mockArgs: { userId: 'demo-user-1' }");
    } else {
      for (final String r in routes) {
        out.writeln("  - name: '$r'");
        out.writeln('    mockArgs: {}');
      }
    }
    out.writeln();
    out.writeln('reference:');
    out.writeln('  opacity: 0.5');
    out.writeln('  blend: difference # off | opacity | difference');
    out.writeln();
    out.writeln('lint:');
    out.writeln('  enabled: true');
    out.writeln('  tolerance: 0 # allowed numeric drift before flagging, e.g. 0.5');
    return out.toString();
  }

  String? mergeRoutes(String existingYaml, List<String> discoveredRoutes) {
    final Set<String> existingNames =
        const ConfigLoader().loadFromString(existingYaml).routes.map((r) => r.name).toSet();
    final List<String> newRoutes =
        discoveredRoutes.where((String r) => !existingNames.contains(r)).toList();
    if (newRoutes.isEmpty) return null;

    final String newLines =
        newRoutes.map((String r) => "  - name: '$r'\n    mockArgs: {}").join('\n');

    final RegExp routesKey = RegExp(r'^routes:\s*$', multiLine: true);
    if (!routesKey.hasMatch(existingYaml)) {
      final String sep = existingYaml.endsWith('\n') ? '' : '\n';
      return '$existingYaml$sep\nroutes:\n$newLines\n';
    }

    final List<String> lines = existingYaml.split('\n');
    final int idx = lines.indexWhere((String l) => routesKey.hasMatch('$l\n'));
    int insertAt = lines.length;
    for (int i = idx + 1; i <= lines.length; i++) {
      if (i == lines.length || (lines[i].trim().isNotEmpty && !lines[i].startsWith(' '))) {
        insertAt = i;
        break;
      }
    }
    lines.insert(insertAt, newLines);
    return lines.join('\n');
  }

  String _fmt(double v) => v == v.roundToDouble() ? v.toInt().toString() : v.toString();
}
